* EmbArBB
  + Embedded language for data parallel programming targetting Intel ArBB. 
  + Uses the Haskell/ArBB bindings (svenssonjoel/arbb-vm.git on github)

* Status
  + The samples and benchmarks now run again 
    
* TODOs:  
  + Think up some new execute interface. 
 
  + print function for DAGs
   
  + Things like mkScalar needs to be separated from the specific backend. 

  + The make_ref_countable family of functions in the arbb-vm needs to be understood. 
    Currently things stored on the ArBB heap are not freed. Manual freeing 
    of vectors does not sound very attractive so figuring out some way to automate this 
    is important. 

  + 'copyIn', 'copyOut' and 'new' functions for NVectors. 
    
  + See if there is a point to having some set of "immediate functions" that can 
    be executed directly in an withArBB session. 

  + Array of Tuple to Tuple of Array compilation step

  + Support more general looping states. 

  + Keep track of what functions have been captured. If a function uses "Call"  on 
    the same other function many times, each of these calls will lead to a captured 
    instance of that function. Some map of "functionHash -> functionID" is needed. 
    A way to get unique identifiers from a GenRecord could do as the hash

* NOTES: 
  + An ArBB function cannot "Call" itself. That is, ArBB functions 
    cannot be recursive. To upweigh this there are many forms of loops, 
    Do, While, For. 
  + The nested vector capabilities feel a bit wing-clipped from the 
    missing recursion. Finding a few example apps that use the nested 
    vectors might cast some light.
 



