* EmbArBB 
  + Embedded language for data-parallel programming targetting Intel ArBB.
  + very sketchy! (But improving) 
  + Uses the Haskell/ArBB bindings (svenssonjoel/arbb-vm.git on github) 

* Status 
  + Generates ArBB functions from functions in the embedded language. 
  + A subset of ArBB functionality is implemented. 

* Problems
  + Right now there are two kinds of Scalars. 
    Exp a and Exp (DVector Dim0 a) (for scalar a).
    Should there be only one ? If so, then Exp (DVector Dim0 a) will be the one. 

* TODOs 
  + Add functionality (cover as many as possible of the ops supported by ArBB) 
  + Figure out how to capture functions with many outputs. 
    
* Notes
  + ArBB Supplies the operations Rotate and RotateRev to the programmer. It seems 
    to me that RotateRev is compiled into a Rotate operation with a negated distance. 
  + Scan direction seems broken. Setting direction to 0 and 1 gives same resulting 
    output array (or did i missunderstand what the direction is supposed to mean).
