

all: 
#	ghc --make histogram.hs -i../
#	ghc --make saxpy.hs -i../
#	ghc --make matrix_mult.hs -i../
#	ghc --make matrix_vector.hs -i../
#	ghc --make sgemm.hs -i../
	ghc --make addconst.hs -i../
#	ghc --make simplemap.hs -i../
	ghc --make sobel.hs -i../ 
#	ghc --make dotprod.hs -i../


clean: 
	rm histogram
	rm saxpy
	rm matrix_mult
	rm matrix_vector
	rm sgemm
	rm sobel
	rm dotprod 
	rm *.o
	rm *.h