

all: 
	ghc --make histogram.hs -i../
	ghc --make saxpy.hs -i../
	ghc --make matrix_mult.hs -i../
	ghc --make matrix_vector.hs -i../
	ghc --make sgemm.hs -i../
	ghc --make addconst.hs -i../


clean: 
	rm histogram
	rm saxpy
	rm matrix_mult
	rm matrix_vector
	rm sgemm
	rm *.o
	rm *.hi